#!/usr/bin/env python3
# -*- coding:utf-8 -*-
import re
import socket
import i3pystatus
from i3pystatus.updates import aptget

status = i3pystatus.Status(standalone=True)
# Basic info
status.register("clock")
if socket.gethostname() == 'charon':
    status.register("battery")
status.register("updates", backends=aptget.AptGet())
status.register("load")
status.register("uptime")
if socket.gethostname() != 'orphee': status.register("temp")
status.register("cpu_usage_graph")
status.register("mem_bar")
status.register("disk",
        path           = "/",
        format         = "/: {avail}Go",
        display_limit  = 15,
        critical_limit = 5)
if socket.gethostname() == 'pollivier-deb':
    status.register("disk",
            path           = "/home",
            format         = "/home: {avail}Go",
            display_limit  = 40,
            critical_limit = 10)
    status.register("disk",
            path           = "/mnt/space",
            format         = "space: {avail}Go",
            display_limit  = 100,
            critical_limit = 50)


# Music info
status.register("pulseaudio")
if re.match('[a-z]+\.home', socket.getfqdn()):
    mpd_args = {'host': 'mpd.home'}
else:
    mpd_args = {'host': 'localhost'}

status.register("mpd",
                format="{status} {title} by {artist} on {album}",
                status={
                    "pause" : "▷",
                    "play"  : "▶",
                    "stop"  : "◾"},
                **mpd_args)

# FIRING DA LAZER !
status.run()
